--EX1:
SELECT
    DISTINCT CITY
FROM station
WHERE ID % 2 =0
ORDER BY CITY

--EX2:
SELECT
    COUNT(*) - COUNT(DISTINCT CITY) AS 'DIFFERENCE'
FROM STATION

--EX3:
---BÀI VỀ LOẠI BỎ SỐ 0 CÓ TRRONG DÃY SỐ VÀ THỰC HIỆN TÍNH TOÁN
--EX4:
SELECT
  ROUND(CAST(SUM(ITEM_COUNT*ORDER_OCCURRENCES) / SUM(ORDER_OCCURRENCES) AS DECIMAL),1) AS "MEAN"
FROM items_per_order

--EX5:
SELECT
  CANDIDATE_ID
FROM candidates
WHERE SKILL IN ('Python','Tableau','PostgreSQL')
GROUP BY CANDIDATE_ID
HAVING COUNT(SKILL) = 3

--EX6:
SELECT
  USER_ID,
  MAX(DATE(POST_DATE)) - MIN(DATE(POST_DATE)) AS "DAYS_BETWEEN"
FROM posts
WHERE POST_DATE BETWEEN '2021-01-01' AND '2022-01-01'
GROUP BY USER_ID
HAVING COUNT(POST_DATE) >= 2

--EX7:
SELECT
  card_name,
  MAX(issued_amount) - MIN(issued_amount) AS "DIFFERENCE"
FROM monthly_cards_issued
GROUP BY card_name
ORDER BY "DIFFERENCE" DESC

--EX8:
--TÊN NSX GÂY RA TỔN THẤT, SỐ LOẠI THUỐC CÓ TỔN THẤT, TỔNG TỔN THẤT
SELECT
  manufacturer,
  COUNT(drug),
  ABS(SUM(total_sales - cogs)) AS "TOTAL_LOSS"
FROM pharmacy_sales
WHERE total_sales - cogs < 0
GROUP BY manufacturer
ORDER BY "TOTAL_LOSS" DESC

--EX9:
SELECT*
FROM CINEMA
WHERE ID % 2 >0 AND DESCRIPTION != 'boring'
ORDER BY RATING DESC

--EX10:
SELECT
    TEACHER_ID,
    COUNT(DISTINCT SUBJECT_ID) AS CNT
FROM TEACHER
GROUP BY TEACHER_ID
ORDER BY CNT

--EX11:
SELECT
    USER_ID,
    COUNT(FOLLOWER_ID) AS 'FOLLOWERS_COUNT'
FROM FOLLOWERS
GROUP BY USER_ID
ORDER BY USER_ID

--EX12:
SELECT
    CLASS
FROM COURSES
GROUP BY CLASS
HAVING COUNT(STUDENT) >= 5
ORDER BY CLASS
