--EX1:
SELECT
NAME
FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME,3), ID 

--EX2:
SELECT
USER_ID,
CONCAT(UPPER(LEFT(NAME,1)),LOWER(RIGHT(NAME,LENGTH(NAME)-1))) AS NAME
FROM USERS
ORDER BY USER_ID

--EX:3:
SELECT
MANUFACTURER,
'$' || ROUND((SUM(TOTAL_SALES)/1000000),0) || ' ' || 'million' AS SALE
FROM pharmacy_sales
GROUP BY MANUFACTURER
ORDER BY SUM(TOTAL_SALES) DESC, MANUFACTURER

--EX4:
SELECT
EXTRACT(MONTH FROM SUBMIT_DATE) AS MTH,
PRODUCT_ID AS PRODUCT,
ROUND(AVG(STARS),2) AS AVG_STARS
FROM reviews
GROUP BY PRODUCT_ID, EXTRACT(MONTH FROM SUBMIT_DATE)
ORDER BY MTH, PRODUCT_ID

--EX5:
SELECT
SENDER_ID,
COUNT(MESSAGE_ID) AS MESSAGE_COUNT
FROM messages
WHERE EXTRACT(MONTH FROM SENT_DATE) = 8 AND EXTRACT(YEAR FROM SENT_DATE) = 2022
GROUP BY SENDER_ID
ORDER BY MESSAGE_COUNT DESC
LIMIT 2

--EX6:
SELECT
TWEET_ID
FROM TWEETS
WHERE LENGTH(CONTENT) > 15

--EX7:
SELECT
activity_date AS DAY,
COUNT(DISTINCT USER_ID) AS ACTIVE_USERS
FROM ACTIVITY
WHERE activity_date BETWEEN '2019-06-28' AND '2019-07-29'
GROUP BY activity_date

--EX8:
SELECT
COUNT(id)
FROM employees
WHERE joining_date BETWEEN '2021-01-01' AND '2021-07-31'

--EX9:
SELECT
POSITION ('a' IN first_name) AS POSITION
FROM worker
WHERE first_name = 'Amitah'

--EX10:
SELECT
winery,
SUBSTRING(title FROM LENGTH(winery)+2 FOR 4) AS YEAR
FROM winemag_p2
WHERE country = 'Macedonia'














